# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/GUI/VLQRISC.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1256, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.reg_table = QtWidgets.QTableView(self.centralwidget)
        self.reg_table.setGeometry(QtCore.QRect(840, 30, 401, 581))
        self.reg_table.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.reg_table.setObjectName("reg_table")
        self.memory_table = QtWidgets.QTableView(self.centralwidget)
        self.memory_table.setGeometry(QtCore.QRect(20, 160, 811, 451))
        self.memory_table.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.memory_table.setObjectName("memory_table")
        self.update_reg_tbl_btn = QtWidgets.QPushButton(self.centralwidget)
        self.update_reg_tbl_btn.setGeometry(QtCore.QRect(720, 10, 101, 31))
        self.update_reg_tbl_btn.setObjectName("update_reg_tbl_btn")
        self.command_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.command_entry.setGeometry(QtCore.QRect(20, 10, 691, 31))
        self.command_entry.setObjectName("command_entry")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 50, 71, 41))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.instruction_output_lbl = QtWidgets.QLabel(self.centralwidget)
        self.instruction_output_lbl.setGeometry(QtCore.QRect(540, 50, 281, 41))
        self.instruction_output_lbl.setAutoFillBackground(True)
        self.instruction_output_lbl.setText("")
        self.instruction_output_lbl.setObjectName("instruction_output_lbl")
        self.error_label = QtWidgets.QLabel(self.centralwidget)
        self.error_label.setGeometry(QtCore.QRect(200, 50, 251, 81))
        self.error_label.setAutoFillBackground(False)
        self.error_label.setStyleSheet("QLabel{border: 1px solid black;}")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.error_label.setObjectName("error_label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 181, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(840, 10, 101, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 60, 16))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1256, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VLQRISC Simulator"))
        self.update_reg_tbl_btn.setText(_translate("MainWindow", "Execute"))
        self.label.setText(_translate("MainWindow", "Instruction inputed:"))
        self.label_2.setText(_translate("MainWindow", "Result from last instruction:"))
        self.label_3.setText(_translate("MainWindow", "Registers:"))
        self.label_4.setText(_translate("MainWindow", "Memory"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
